export const UPDATE_SIGNUP_DATA = "SIGNUP/UPDATE_SIGNUP_DATA";
export const CLEAR_SIGNUP_DATA = "SIGNUP/CLEAR_SIGNUP_DATA";
export const UPDATE_PLACE_DATA = "PLACE/UPDATE_PLACE_DATA";
export const CLEAR_PLACE_DATA = "PLACE/CLEAR_PLACE_DATA";
